spring:
    datasource:
        password: ''
        url: jdbc:mysql://127.0.0.1:3306/users_db?createDatabaseIfNotExist=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
        show-sql: true
#logging:
#    level:
#        root: ERROR
#        org:
#            springframework: DEBUG
